#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Advisor_Sidekick_V2.Resource", IsApplication=true)]

namespace Advisor_Sidekick_V2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04003a
			public const int addressEditBox = 2130968634;
			
			// aapt resource value: 0x7f040039
			public const int addressTextBox = 2130968633;
			
			// aapt resource value: 0x7f040006
			public const int checkBox1 = 2130968582;
			
			// aapt resource value: 0x7f04000f
			public const int checkBox10 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int checkBox11 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int checkBox12 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int checkBox13 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int checkBox14 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int checkBox15 = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int checkBox16 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int checkBox17 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int checkBox18 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int checkBox19 = 2130968600;
			
			// aapt resource value: 0x7f040007
			public const int checkBox2 = 2130968583;
			
			// aapt resource value: 0x7f040019
			public const int checkBox20 = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int checkBox21 = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int checkBox22 = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int checkBox23 = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int checkBox24 = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int checkBox25 = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int checkBox26 = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int checkBox27 = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int checkBox28 = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int checkBox29 = 2130968610;
			
			// aapt resource value: 0x7f040008
			public const int checkBox3 = 2130968584;
			
			// aapt resource value: 0x7f040023
			public const int checkBox30 = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int checkBox31 = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int checkBox32 = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int checkBox33 = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int checkBox34 = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int checkBox35 = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int checkBox36 = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int checkBox37 = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int checkBox38 = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int checkBox39 = 2130968620;
			
			// aapt resource value: 0x7f040009
			public const int checkBox4 = 2130968585;
			
			// aapt resource value: 0x7f04002d
			public const int checkBox40 = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int checkBox41 = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int checkBox42 = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int checkBox43 = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int checkBox44 = 2130968625;
			
			// aapt resource value: 0x7f04000a
			public const int checkBox5 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int checkBox6 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int checkBox7 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int checkBox8 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int checkBox9 = 2130968590;
			
			// aapt resource value: 0x7f04003f
			public const int emailEditBox = 2130968639;
			
			// aapt resource value: 0x7f04003e
			public const int emailTextBox = 2130968638;
			
			// aapt resource value: 0x7f040036
			public const int firstNameEditBox = 2130968630;
			
			// aapt resource value: 0x7f040035
			public const int firstNameTextBox = 2130968629;
			
			// aapt resource value: 0x7f04003d
			public const int highschoolEditBox = 2130968637;
			
			// aapt resource value: 0x7f04003c
			public const int highschoolTextBox = 2130968636;
			
			// aapt resource value: 0x7f040038
			public const int lastNameEditBox = 2130968632;
			
			// aapt resource value: 0x7f040037
			public const int lastNameTextBox = 2130968631;
			
			// aapt resource value: 0x7f040004
			public const int loginButton = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int passwordTBox = 2130968579;
			
			// aapt resource value: 0x7f04003b
			public const int phoneNumberEditBox = 2130968635;
			
			// aapt resource value: 0x7f040005
			public const int registerButton = 2130968581;
			
			// aapt resource value: 0x7f040032
			public const int relativeLayout1 = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int save = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int scrollView1 = 2130968628;
			
			// aapt resource value: 0x7f040000
			public const int textView1 = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int textView2 = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int usernameTbox = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int MajorScreen = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Registration = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
